### PR TITLE
Fix error not thrown in CommandParser

### LINKED ISSUE #458: CommandParser classes should utilize CommandUtil Issues
During implementation of the commands, certain errors are not caught by the parser. 

Image

In particular, instead of new RewardPoints(stringValue), parser classes should use

Image

Because ParserUtil will throw the relevant error that is caught and rendered.

### PR DESCRIPTION
**Pull request by loyaltypollution**
Fixes #458

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/QuickAddCustomerCommandParser.java [hunk 1]
```diff
@@ -51,7 +51,7 @@ public QuickAddCustomerCommand parse(String args) throws ParseException {
                     String.format(MESSAGE_INVALID_COMMAND_FORMAT, QuickAddCustomerCommand.MESSAGE_USAGE));
         }
 
-        CustomerId customerId = new CustomerId(customerInfo[0]);
+        CustomerId customerId = ParserUtil.parseCustomerId(customerInfo[0]);
         Name name = ParserUtil.parseName(customerInfo[1]);
```
Comment (Jsjk112344) [inline src/main/java/seedu/address/logic/parser/QuickAddCustomerCommandParser.java:55]: Should these name and phone fileds also make use of ParserUtil?
