### PR TITLE
Branch fix duplicate customerid

### LINKED ISSUE #312: System allows duplicate CustomerIDs
During alpha testing, I discovered that CaféConnect allows the creation of customers with duplicate ID numbers, which should be unique identifiers.

**Steps to Reproduce:**
1. Add a customer with:
customeradd cid/C001 n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 rp/150 vc/8 fi/Cappuccino ts/120
2. Add another customer with the same ID: 
customeradd cid/C001 n/Duplicate ID p/12345678 e/dup@example.com a/Somewhere rp/100 vc/5 fi/Tea ts/50

Expected Behavior:
The system should reject the second command and display an error message stating that the customer ID already exists.

Actual Behavior:
The second customer is added with the same ID as the first customer.

Additional Notes:
Staff ID validation works correctly - duplicate staff IDs are rejected
This is a critical issue as it breaks the uniqueness constraint for customer IDs

Severity: High

### LINKED ISSUE #321: Duplicate Customer id allowed
Image

should only allow for unique customer id, similar to staff

### PR DESCRIPTION
**Pull request by rannn367**
fixes #321 and also fixes #312

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Customer.java [hunk 1]
```diff
@@ -74,9 +86,13 @@ public boolean isSamePerson(Person otherPerson) {
             return false;
         }
 
-        // Compare using phone as unique identifier
+        // Compare using customerId as unique identifier
         Customer otherCustomer = (Customer) otherPerson;
-        return otherCustomer.getPhone().equals(getPhone());
+
+        boolean isSame = otherCustomer.getCustomerId().equals(getCustomerId());
```
Comment (WhiteBear82) [inline src/main/java/seedu/address/model/person/Customer.java:92]: LGTM. It seems logical to check for equality of two customers using CustomerId, similar to Staff.

**Review by WhiteBear82 — COMMENTED** [review]
LGTM
