### PR TITLE
Make invalid PerformanceRating error message more specific

### LINKED ISSUE #320: Misleading error message for invalid field for Staff
Image

Image

Performance rating that should be valid throws an error message.

### Steps to recreate
`staffedit 1 rating/3.22`

### Expected
either throw an error to say rating can only take 1 decimal place, or automatically round down the rating if rating is more than 1d.p.

### Actual
even though rating is in between 0 and 5.0 inclusive, (3.22 is in between), but it throws an error message to say  that the number is wrong and should be in between the values when it already is.

### PR DESCRIPTION
**Pull request by rannn367**
fixes #320

### CODE REVIEW

File: src/main/java/seedu/address/model/person/PerformanceRating.java [hunk 1]
```diff
@@ -10,7 +10,7 @@
 public class PerformanceRating {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Performance rating should be a number between 0 and 5.0 (inclusive).";
+            "Performance rating should be a number between 0 and 5.0 (inclusive) with at most one decimal place.";
```
Comment (WhiteBear82) [inline src/main/java/seedu/address/model/person/PerformanceRating.java:13]: This error message is now more specific thus would definitely be more informative to the user.

**Review by WhiteBear82 — COMMENTED** [review]
It is good how you considered the user perspectives in terms of a detailed error message.
